### ISSUE TITLE
Call not auto disconnected (At least on Huawei Modem)

### ISSUE THREAD

**Issue by vineetchaudhary** [tdelenikas/smslib#5]
I'm using Huawei 1550 modem on Mac OSX. When I receive a call on the modem, CLIP is shown and ATH command is sent to disconnect the call. But the call is not disconnected.
Solution:
While configuring modem properties after sending AT+CLIP=1, we also need to send AT+CVHU=0 so that call can be connected with ATH command.

**Comment by tdelenikas** [comment]
Edit `modem.properties` and modify

`huawei.init2=AT^CURC=0\r`

to

`huawei.init2=AT^CURC=0\rAT+CVHU=0\r`

Rebuild and try once more. If this works, I would require your modem signature (http://smslib.org/doc/v4/ModemConfiguration) in order to properly add it in the standard distro.

Otherwise, let me know... Thanks.

**Comment by vineetchaudhary** [comment]
Thanks, Will try it out.
I anyway rebuilt by adding a dirty hack :

protected ModemResponse atEnableClip() throws Exception
    {
        write("AT+CVHU=0\r");
                return write("AT+CLIP=1\r");
    }

:-)

**Comment by vineetchaudhary** [comment]
This comment is to appreciate the work that you have done.
This is a very nicely written and really helpful library and saved me a lot of time and effort.
Keep up the good work :+1:

**Comment by tdelenikas** [comment]
Hi,

Did you by any chance try the "official" solution?
